# Generated by Django 5.2.1 on 2025-05-21 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fidelidad', models.CharField(max_length=50)),
                ('beneficios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sabor', models.CharField(max_length=50)),
                ('cantidadLimite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=50)),
                ('apeEmp', models.CharField(max_length=50)),
                ('numeroTelefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('idcategoria_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriacliente')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioporPorcion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.TextField()),
                ('idcategoria_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaextra')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadTotalPlatos', models.IntegerField()),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('idmesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(max_length=50)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('personalizable', models.BooleanField(default=False)),
                ('idcategoria_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaplato')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioBasePlato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precioFinalPlato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipoPedido', models.CharField(max_length=50)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('idplato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plato')),
            ],
        ),
        migrations.CreateModel(
            name='ExtrasPlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioPersonalizacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idextra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extras')),
                ('idplato_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.platopedido')),
            ],
        ),
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
    ]
